paths:
  input_path: "Projects/qa_cleaning__and_aug/data/input/input_qa.csv"
  cleaned_path: "Projects/qa_cleaning__and_aug/data/processed_dataset/cleaned_qa.csv"
  #augmented_path: "data/output/augmented_qa.csv"

models:
  llama_version: "3"
  paraphraser: tuner007/pegasus_paraphrase
  back_translation:
    en_to_fr: Helsinki-NLP/opus-mt-en-fr
    fr_to_en: Helsinki-NLP/opus-mt-fr-en
    
  fitb_model_id: "google/flan-t5-large"
  fitb_max_new_tokens: 100
  fitb_temperature: 0.7
  mcq_model_id: "meta-llama/Llama-3.2-3B-Instruct"

  mlm:
    model_id: bert-base-uncased
    max_replacements: 3

  typo_noise:
    aug_char_min: 1
    aug_char_max: 1
    aug_char_p: 0.01



llm:
  temperature: 0.7
  max_tokens: 512
  batch_size: 10
